apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: enquete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        envFrom:
        - secretRef:
            name: db-secret
        volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready","-U","postgres"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: enquete
spec:
  selector:
    app: db
  ports:
  - port: 5432
